name: Bug Report
description: Create a bug report
labels: [bug]
body:
  - type: textarea
    id: the-bug
    attributes:
      label: What happened?
      description: What you expected to see? What you actually saw? Please provide the steps to reproduce the bug.
      placeholder: A bug happened!
    validations:
      required: true
  - type: dropdown
    id: minecraft-version
    attributes:
      label: Minecraft Version
      description: Minecraft Version
      options:
        - "1.21.11"
        - "1.21.10"
        - "1.21.7/1.21.8"
        - "1.21.5"
    validations:
      required: true
  - type: input
    id: cariboustonks-version
    attributes:
      label: CaribouStonks Version
      description: What version of CaribouStonks are you running?
      placeholder: ex. CaribouStonks-0.9.1+1.21.10.jar
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      placeholder: You can add images
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Log output
      description: 'You can upload a client log file (ex. latest.log) by dragging and dropping it into this section. You can also paste your log file on this website: https://mclo.gs and share the link!'
    validations:
      required: false
  - type: textarea
    id: other
    attributes:
      label: Other
      description: Please include other helpful information below
    validations:
      required: false
