name: Build
on: [ push, pull_request ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          # gradle-home-cache-cleanup: true
          validate-wrappers: true

      - name: Run Checkstyle
        run: ./gradlew checkstyleMain

      - name: Capture Checkstyle reports
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: checkstyle-reports
          path: |
            **/build/reports/checkstyle/

      - name: Run Tests
        run: ./gradlew test

      - name: Capture test results
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: test-results
          path: |
            **/build/reports/tests/
            **/build/test-results/

      - name: Gradle Build
        run: ./gradlew build -x test

      - name: Capture other build reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: other-reports
          path: |
            **/build/reports/
            !**/build/reports/tests/
            !**/build/reports/checkstyle/

      - name: Capture build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: build/libs/
